sides = input("how many sides do your dice have? ")
dice = input("how many dice do you want to roll? ")
num = input("what number do you want to find the probability of being the highest rolled when those dice are rolled? ")
sides = int(sides)
dice = int(dice)
num = int(num)
probability = (1/(sides**dice))*((num**dice)-((num-1)**dice))
cases = ((num**dice)-((num-1)**dice))
print (num,"being the highest number when you roll",dice,sides,"sided dice has a",probability*100,"percent chance of happening")
print ("out of all possible combinations of",dice,sides,"sided dice",num,"would be the highest number rolled in",cases,"of them")
print ("there are a total of",sides**dice,"combinations of",dice,sides,"sided dice!")
